name: Manage releases

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please! 🤖
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4
        id: release
      - name: Checkout 🛎️
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Set up NPM 🔧
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 24
          registry-url: "https://registry.npmjs.org"
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Install dependencies 🔧
        run: npm ci
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Build package 🔧
        run: npm run build --if-present
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Build image 🔧
        run: docker build -t ghcr.io/eox-a/git-clerk:${{ steps.release.outputs.tag_name }} .
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Login ghcr 🔧
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
      - name: Push ghcr 🚀
        run: docker push ghcr.io/eox-a/git-clerk:${{ steps.release.outputs.tag_name }}
        if: ${{ fromJSON(steps.release.outputs.releases_created) }}
