name: Run tests

on:
  pull_request:
    branches:
      - "main"
      - "**/main"
      - "!release-please*"
    types:
      - opened
      - reopened
      - synchronize

jobs:
  run-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [24]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
        # necessary for git diff of changed files in the PR
        with:
          fetch-depth: 2

      - name: Setup node env 🏗
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Cache node_modules 📦
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Cache Cypress binary 📦
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: ~/.cache/Cypress
          key: ${{ runner.os }}-cypress-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-cypress-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Install Cypress binary 🏗
        run: npx cypress install

      - name: Start server 💻
        run: npm run test:serve &
        env:
          CI: true
          GITCLERK_GITHUB_REPO: octocat/Hello-World
          GITCLERK_GITHUB_TOKEN: dummy-token

      - name: Wait for server to be ready 💻
        run: npx wait-on http://localhost:3000

      - name: Run Cypress tests 👀
        run: npm run test:ga

      - name: Upload failed test screenshots 📷
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
